// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// Provide a minimal declaration for `process` to satisfy TypeScript when
// @types/node is not installed or 'node' types are not enabled in tsconfig.
//declare const process: { env: { [key: string]: string | undefined } };

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});